// AUTO-GENERATED by scripts/calibrate-form-fields.ts — do not edit by hand.
// Normalized (0..1) rectangles, origin top-left, against each rendered page.
// Regenerate whenever an official DOCX master changes.

export type FieldRect = { page: number; x: number; y: number; w: number; h: number };
export type FormFieldMap = Record<string, FieldRect[]>;

export const FORM_FIELD_MAPS: Record<string, FormFieldMap> = {
  "SF001": {
    "orgName": [
      {
        "page": 1,
        "x": 0.7139,
        "y": 0.3106,
        "w": 0.075,
        "h": 0.0184
      },
      {
        "page": 1,
        "x": 0.6048,
        "y": 0.6835,
        "w": 0.1037,
        "h": 0.0184
      }
    ],
    "date": [
      {
        "page": 1,
        "x": 0.8135,
        "y": 0.1904,
        "w": 0.0659,
        "h": 0.0184
      }
    ],
    "presidentName": [
      {
        "page": 1,
        "x": 0.5443,
        "y": 0.6384,
        "w": 0.1099,
        "h": 0.0184
      }
    ],
    "adviserName": [
      {
        "page": 1,
        "x": 0.121,
        "y": 0.7287,
        "w": 0.0883,
        "h": 0.0184
      }
    ]
  },
  "SF002": {
    "orgName": [
      {
        "page": 1,
        "x": 0.2768,
        "y": 0.3414,
        "w": 0.0872,
        "h": 0.02
      },
      {
        "page": 1,
        "x": 0.6653,
        "y": 0.5763,
        "w": 0.1187,
        "h": 0.02
      }
    ],
    "date": [
      {
        "page": 1,
        "x": 0.7707,
        "y": 0.1843,
        "w": 0.0763,
        "h": 0.02
      }
    ],
    "presidentName": [
      {
        "page": 1,
        "x": 0.6653,
        "y": 0.5107,
        "w": 0.1118,
        "h": 0.02
      }
    ],
    "deanName": [
      {
        "page": 1,
        "x": 0.2038,
        "y": 0.7048,
        "w": 0.0744,
        "h": 0.02
      }
    ],
    "adviserName": [
      {
        "page": 1,
        "x": 0.1613,
        "y": 0.6556,
        "w": 0.102,
        "h": 0.02
      }
    ]
  },
  "SF003": {
    "orgName": [
      {
        "page": 1,
        "x": 0.1609,
        "y": 0.3637,
        "w": 0.1129,
        "h": 0.02
      }
    ],
    "date": [
      {
        "page": 1,
        "x": 0.7801,
        "y": 0.1836,
        "w": 0.0729,
        "h": 0.0192
      },
      {
        "page": 1,
        "x": 0.6618,
        "y": 0.6422,
        "w": 0.0648,
        "h": 0.02
      }
    ],
    "ay": [
      {
        "page": 1,
        "x": 0.3094,
        "y": 0.3964,
        "w": 0.0743,
        "h": 0.02
      }
    ],
    "deanName": [
      {
        "page": 1,
        "x": 0.2419,
        "y": 0.7065,
        "w": 0.076,
        "h": 0.02
      }
    ],
    "adviserInfoName": [
      {
        "page": 1,
        "x": 0.641,
        "y": 0.5112,
        "w": 0.0997,
        "h": 0.02
      }
    ],
    "adviserInfoCollege": [
      {
        "page": 1,
        "x": 0.6426,
        "y": 0.5602,
        "w": 0.1201,
        "h": 0.02
      }
    ]
  },
  "SF004": {
    "orgName": [
      {
        "page": 1,
        "x": 0.4308,
        "y": 0.2056,
        "w": 0.1386,
        "h": 0.0233
      }
    ],
    "ay": [
      {
        "page": 1,
        "x": 0.5373,
        "y": 0.2575,
        "w": 0.1025,
        "h": 0.0233
      }
    ],
    "presidentName": [
      {
        "page": 1,
        "x": 0.6048,
        "y": 0.5478,
        "w": 0.1118,
        "h": 0.02
      }
    ],
    "secretaryName": [
      {
        "page": 1,
        "x": 0.1706,
        "y": 0.5642,
        "w": 0.1115,
        "h": 0.02
      }
    ],
    "deanName": [
      {
        "page": 1,
        "x": 0.1613,
        "y": 0.7117,
        "w": 0.076,
        "h": 0.02
      }
    ],
    "adviserName": [
      {
        "page": 1,
        "x": 0.1613,
        "y": 0.6626,
        "w": 0.0975,
        "h": 0.02
      }
    ]
  },
  "SF005": {
    "orgName": [
      {
        "page": 1,
        "x": 0.3579,
        "y": 0.2084,
        "w": 0.1094,
        "h": 0.02
      }
    ],
    "ay": [
      {
        "page": 1,
        "x": 0.6049,
        "y": 0.18,
        "w": 0.0866,
        "h": 0.02
      }
    ],
    "semester": [
      {
        "page": 1,
        "x": 0.3931,
        "y": 0.18,
        "w": 0.1059,
        "h": 0.02
      }
    ],
    "deanName": [
      {
        "page": 1,
        "x": 0.1814,
        "y": 0.7712,
        "w": 0.0807,
        "h": 0.02
      }
    ],
    "adviserName": [
      {
        "page": 1,
        "x": 0.1613,
        "y": 0.6934,
        "w": 0.0962,
        "h": 0.02
      }
    ]
  },
  "SF006": {
    "orgName": [
      {
        "page": 1,
        "x": 0.6742,
        "y": 0.4167,
        "w": 0.1133,
        "h": 0.02
      }
    ],
    "date": [
      {
        "page": 1,
        "x": 0.8077,
        "y": 0.2275,
        "w": 0.0716,
        "h": 0.02
      }
    ],
    "deanName": [
      {
        "page": 1,
        "x": 0.1613,
        "y": 0.6363,
        "w": 0.0807,
        "h": 0.02
      }
    ],
    "adviserName": [
      {
        "page": 1,
        "x": 0.1613,
        "y": 0.5708,
        "w": 0.0962,
        "h": 0.02
      }
    ],
    "certifiedStudentName": [
      {
        "page": 1,
        "x": 0.3209,
        "y": 0.3286,
        "w": 0.1117,
        "h": 0.02
      }
    ],
    "certifiedStudentCourseYearSection": [
      {
        "page": 1,
        "x": 0.3002,
        "y": 0.3632,
        "w": 0.113,
        "h": 0.02
      }
    ]
  }
};
