-- CreateEnum
CREATE TYPE "AttachmentKind" AS ENUM ('CONSTITUTION', 'PLAN_OF_ACTIVITIES', 'ACCOMPLISHMENT_REPORTS', 'ADVISER_COMMITMENT', 'CERTIFICATION', 'FINANCIAL_REPORT');

-- AlterTable
ALTER TABLE "Attachment" ADD COLUMN     "kind" "AttachmentKind";
