import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { generateOfficialDocx, type FormData } from "../src/lib/docx/forms";
import { docxToPdf } from "../src/lib/documents/pdf";
import { FORM_DRAFT_FIELDS } from "../src/lib/form-draft-data";

// ---------------------------------------------------------------------------
// Field-map calibration.
//
// Fills every editable draft field with a unique ASCII sentinel, renders the
// populated official DOCX to PDF via the same production pipeline, then locates
// each sentinel in the PDF text layer. The resulting normalized rectangles are
// the exact screen positions where real values land — no hand-tuning.
//
// Re-run whenever an official master template changes:
//   npx tsx --tsconfig scripts/tsconfig.calibrate.json scripts/calibrate-form-fields.ts
// ---------------------------------------------------------------------------

const FORMS = ["SF001", "SF002", "SF003", "SF004", "SF005", "SF006"] as const;

const SENTINELS: Record<string, string> = {
  orgName: "SENorgName",
  date: "SENdate",
  ay: "2098-2099",
  semester: "SENsemester",
  presidentName: "SENpresident",
  secretaryName: "SENsecretary",
  deanName: "SENdean",
  adviserName: "SENadviser",
  adviserInfoName: "SENadvInfo",
  adviserInfoCollege: "SENadvCollege",
  certifiedStudentName: "SENcertStudent",
  certifiedStudentCourseYearSection: "SENcertCYS",
};

function sentinelData(): FormData {
  const s = SENTINELS;
  return {
    orgName: s.orgName,
    date: s.date,
    ay: s.ay,
    semester: s.semester,
    president: { name: s.presidentName, sig: null },
    secretary: { name: s.secretaryName, sig: null },
    advisers: [{ name: s.adviserName, sig: null }],
    dean: { name: s.deanName, sig: null },
    adviserInfo: { name: s.adviserInfoName, college: s.adviserInfoCollege },
    certifiedStudent: {
      name: s.certifiedStudentName,
      courseYearSection: s.certifiedStudentCourseYearSection,
      position: "SENcertPos",
    },
    members: [{ name: "SENmember1", studentNo: "SENno1", courseYearSection: "SENcys1", sig: null }],
  };
}

type Rect = { page: number; x: number; y: number; w: number; h: number };
type FieldMap = Record<string, Rect[]>;

type TextItem = { str: string; transform: number[]; width: number };

async function calibrateForm(
  formKey: string,
  pdfjs: typeof import("pdfjs-dist/legacy/build/pdf.mjs")
): Promise<{ pageCount: number; map: FieldMap }> {
  const docx = await generateOfficialDocx({ formKey, data: sentinelData() });
  const pdf = await docxToPdf(Buffer.from(docx));
  const doc = await pdfjs.getDocument({
    data: new Uint8Array(pdf),
    useSystemFonts: true,
    disableFontFace: true,
  }).promise;

  const itemsByPage: { items: TextItem[]; w: number; h: number }[] = [];
  for (let p = 1; p <= doc.numPages; p += 1) {
    const page = await doc.getPage(p);
    const viewport = page.getViewport({ scale: 1 });
    const tc = await page.getTextContent();
    itemsByPage.push({
      items: tc.items
        .filter((it): it is typeof it & TextItem => "str" in it)
        .map((it) => ({ str: it.str, transform: (it as TextItem).transform, width: (it as TextItem).width })),
      w: viewport.width,
      h: viewport.height,
    });
  }

  const map: FieldMap = {};
  for (const field of FORM_DRAFT_FIELDS) {
    const sentinel = SENTINELS[field.key];
    if (!sentinel) continue;
    const rects: Rect[] = [];
    itemsByPage.forEach(({ items, w, h }, pi) => {
      for (const it of items) {
        const idx = it.str.indexOf(sentinel);
        if (idx < 0) continue;
        const tx = pdfjs.Util.transform(
          [1, 0, 0, -1, 0, h], // viewport transform at scale 1 (flip y)
          it.transform
        );
        const fontSize = Math.hypot(it.transform[2], it.transform[3]);
        const charW = it.width / it.str.length;
        const xPt = tx[4] + idx * charW;
        const wPt = sentinel.length * charW;
        rects.push({
          page: pi + 1,
          x: +(xPt / w).toFixed(4),
          y: +((tx[5] - fontSize * 0.22) / h).toFixed(4),
          w: +(wPt / w).toFixed(4),
          h: +((fontSize * 1.4) / h).toFixed(4),
        });
      }
    });
    if (rects.length > 0) map[field.key] = rects;
  }
  return { pageCount: doc.numPages, map };
}

async function main() {
  const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs");
  const result: Record<string, FieldMap> = {};
  for (const formKey of FORMS) {
    const { pageCount, map } = await calibrateForm(formKey, pdfjs);
    result[formKey] = map;
    const fields = Object.keys(map);
    const rectCount = fields.reduce((n, k) => n + map[k].length, 0);
    console.log(`${formKey}: ${pageCount} page(s), ${fields.length} fields, ${rectCount} rects — ${fields.join(", ")}`);
  }

  const out = `// AUTO-GENERATED by scripts/calibrate-form-fields.ts — do not edit by hand.
// Normalized (0..1) rectangles, origin top-left, against each rendered page.
// Regenerate whenever an official DOCX master changes.

export type FieldRect = { page: number; x: number; y: number; w: number; h: number };
export type FormFieldMap = Record<string, FieldRect[]>;

export const FORM_FIELD_MAPS: Record<string, FormFieldMap> = ${JSON.stringify(result, null, 2)};
`;
  const outPath = join(process.cwd(), "src", "lib", "form-field-map.ts");
  await writeFile(outPath, out, "utf8");
  console.log(`wrote ${outPath}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
